### ISSUE TITLE
Anti gringos

### ISSUE THREAD

**Issue by NaldoMota1** [Hyper1025/Mercury#1]
Mano, eu estava procurando um script anti gringos para o meu grupo. Será que você pode me ajudar?

**Comment by Hyper1025** [comment]
Função foi adicionada [nesse commit](https://github.com/Hyper1025/Mercury/commit/5830ef65efe69833e1d72d5fb6ae68312784dec5)

Todos os créditos ao  #[KillovSky](https://github.com/KillovSky)
